cache:
  directories:
    - $HOME/.m2

language: java
jdk: oraclejdk8

install: true

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
