cache:
  directories:
    - $HOME/.m2

language: java
jdk: oraclejdk8

install: true

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true

env:
  global:
  - secure: oMwaAS8CHvoTqBTe0OqfHnTGv0p/qhDXkuozfRz+DZLR+L5QbiJ1bYbSTXRK0D5ZCEdCj3KDG3VCgUjbMI63rxU7FjHMMaIFm7l8dsE1FgF4JIxIUhnChcM/cmgtFwyTtQCfXrJqe12Fo6B22RZ7CpQgiJvCYR1CayT1OEIG3BQOJb1XmACH51RZmt4CfYv5nU9prdZmSihBTQS6H3pX5jUP5loVN+xWtCN/DmxZN+Aja917t8bEkzcnsQarxhEwaEbk69F7ZD+Oc+D59U7NFrebGHeWXh8ZM20+O6+OzSwJWMoH7ura74O4Fhao6mNxjSvgrC41SYeqB8e+tvCsPaX7Q/cy5YGJ78G5LSPLrq4N5tkTg1ZklLuWdR8q56Z0xIFQlsk14ehhYB9TNYQHTS7QFqWkhOwgcqcnsXJJkR8brH8OISsr8tU4lKF6sVNxemnrsxSdzHzqkTW6f8yxWtQGyOgZY3iaoLln0gH0xStHBl4Hc34ckwhbAyZmq0k46D3T8QxtBWvdVj+8/KU26fzlDNdzpvxo5efdbQT/aau0DaInmKDbR8QZ7zn6IeQhHuKwytG5kReZKJ1YNM2d6aoaR5N9q/5JBOgYaGcRYyal3M+7plSAuN2w79AnXoX052pV1TwkTJObBv3QtCb06usZsWhzM5aQztKxj5Aeq8U=
  - secure: gtrV5dLj6apj1nbYY2E+DfmkxNhvIl1GCkgbwAw6dM59NEPUfIbSZsaS5P2J/MfC8UHGBtd1v7IE8w57pycDOfoADQIONEnOPZ7vcb5U+OvYstGXZBUiB2yAzskxJGtqa8sY3rMDwtacV6/4iUs/HzCWEzLXELPtUgFTx9IHq7WjmOkbA4cRYVKTEx733bfjWRt+Hosf1Boyr6RjxqAPfKi6f4ZxsL38EsYPSbvoJqqOzBPIF2V4NoqfUxw1564KNpyLh6qZlqG8iKn1Ij72ptB2iqyqcWTlZ4Qqu18Nv5uBnin7vKaZWzy1tS3Zn0aHdDIzDBqXJ9wnGxsOhMrmYZYoOQ/VPjfSq2FNCubPcrdTULG8qAq818bhDE5vPC1LWN4XeFoUyBWyBJvhPsR2SWv2dF/hZZlJv8Ib5i7ODNrIBN3XNQV9WUKakynqYG2qL+aMJPYTYzhBOY3JH34t8HJbSquFTCMiZrwvGpSFtAvoImJ3Xj65NPxgUtOrpQrCGxq96FW4uYSx6Pk9pmcusZDEVnW9aoFnAMhTBvjovvzFcXYJWtCHqNECzxL84svWw7O9sjxl84476ABRI9YH/tK4iCff8VPDBNRwyeeBsL9fD06Sbu5nvOfzw/4KbloHPYWIadcL14ZvhqJJxgzPNBKapOg/GPkUUArsn8W4O1Q=
